# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 14:50
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=255)),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=12)),
                ('active_participants', models.IntegerField(default=0)),
                ('max_participants', models.IntegerField(default=0)),
                ('logoimgurl', models.CharField(max_length=300, validators=[django.core.validators.URLValidator()])),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=255)),
                ('subscribe', models.BooleanField(default=False)),
                ('subscribe_time', models.IntegerField(null=True)),
                ('sex', models.IntegerField(choices=[(0, b'Not Set'), (1, b'Male'), (2, b'Female')], default=0)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('headimgurl', models.CharField(max_length=300, validators=[django.core.validators.URLValidator()])),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('virtual_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remark', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RunningTask',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=255)),
                ('mode', models.CharField(max_length=255)),
                ('guaranty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('down_payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('duration_days', models.IntegerField()),
                ('distance', models.FloatField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='on.Activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RunningTaskRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time', models.DateTimeField()),
                ('bonus', models.DecimalField(decimal_places=2, max_digits=12)),
                ('distance', models.FloatField(default=0)),
                ('voucher', models.ImageField(blank=True, upload_to=b'')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='on.RunningTask')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
